a=input('Digite alguma coisa: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero?', a.isnumeric())
print('É Alfabetico?', a.isalpha())
print('É Alfanumerico?', a.isalnum())
print('É maiuscula?', a.isupper())
print('É minuscula?', a.islower())
print('É capitalzada?', a.istitle())
